### ISSUE TITLE
Using SSL Certificates

### ISSUE THREAD

**Issue by gerimo** [tiangolo/uwsgi-nginx-flask-docker#36] opened 2018-02-01 19:34 UTC
Hi Tiangolo! Thank you for this.

I'm having a real hard time installing SSL certificates for this docker image.

Is there any additional changes I should implement?

This is how I have modified nginx.conf:

```
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # Redirect all HTTP requests to HTTPS with a 301 Moved Permanently response.
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    # certs sent to the client in SERVER HELLO are concatenated in ssl_certificate
    ssl_certificate /etc/ssl/www.messiac.com.crt;
    ssl_certificate_key /etc/ssl/www.messiac.com.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;

    # Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits
    ssl_dhparam /path/to/dhparam.pem;

    # intermediate configuration. tweak to your needs.
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES1$
    ssl_prefer_server_ciphers on;

    # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
    add_header Strict-Transport-Security max-age=15768000;

    # OCSP Stapling ---
    # fetch OCSP records from URL in ssl_certificate and cache them
    ssl_stapling on;
    ssl_stapling_verify on;

# certs sent to the client in SERVER HELLO are concatenated in ssl_certificate
    ssl_certificate /etc/ssl/www.messiac.com.crt;
    ssl_certificate_key /etc/ssl/www.messiac.com.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;

    # Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits
    ssl_dhparam /path/to/dhparam.pem;

    # intermediate configuration. tweak to your needs.
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES1$
    ssl_prefer_server_ciphers on;

    # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
    add_header Strict-Transport-Security max-age=15768000;

    # OCSP Stapling ---
    # fetch OCSP records from URL in ssl_certificate and cache them
    ssl_stapling on;
    ssl_stapling_verify on;

    ## verify chain of trust of OCSP response using Root CA and Intermediate certs
    ssl_trusted_certificate /etc/ssl/www.messiac.com.crt;

    resolver <IP DNS resolver>;

    ....
}

daemon off;
```

**Comment by tiangolo** [comment] 2018-02-04 14:34
Yep, a little piece of advice: separate TLS / SSL handling from the rest of your app.

It's called ["TLS (SSL) termination"](https://en.wikipedia.org/wiki/TLS_termination_proxy). What you do is set up a high-performance proxy in front of your app, handling all the TLS (HTTPS) stuff, in a different container.

As simple as "changing HTTP to HTTPS" might sound, it's actually a rather complex problem. So, most of the times it's better to separate those 2 concerns.

Also, the only way to have more than one domain in a single IP address (a single server) with TLS (HTTPS) is with a TLS termination proxy. Because TLS works at the TCP level, so, all the HTTPS stuff happens before the server knows the hostname (domain) that is being requested.

---

There are several options, including Nginx and HAProxy, but I suggest you use [Traefik](https://github.com/containous/traefik). It has [very good performance](http://docs.traefik.io/benchmarks/) is very easy to configure and [integrate with Docker](https://docs.traefik.io/configuration/backends/docker/). And it has integrated support for [Let's Encrypt TLS certificate generation and renewal](https://docs.traefik.io/configuration/acme/).

---

You can also check this Flask project generator: https://github.com/senseta-os/senseta-base-project

It is based on this image and has Traefik configuration already set up. You can actually copy the parts you need from the `docker-compose.yml` files.

**Comment by yccheok** [comment] 2018-02-09 20:07
@tiangolo 

Thanks for creating this project. It enables me to setup a web application, with little sysadmin knowledge.

Do you have any plan to include Traefik SSL configuration, so that user with not much sysadmin knowledge, can deploy their web application with SSL traffic?

Thanks.

**Comment by tiangolo** [comment] 2018-02-09 21:08
I'm glad it has helped you.

You can check the Flask project generator here: https://github.com/senseta-os/senseta-base-project. 

It's actually created by me.

It has, among many other features, SSL configuration with Traefik. It even supports multiple stacks (with multiple domains) on the same server, with separated SSL certificates. :smile:

**Comment by Lijo050** [comment] 2018-02-11 10:51
Hi @tiangolo 

I want to use self-signed ssl certificates on nginx and then use it on the container, even then should I handle all the TLS stuff in a different container ?

Thanks

**Comment by tiangolo** [comment] 2018-02-13 10:17
It would be a lot easier to handle all that in a separate container. If you update your app code, create a new image and want to update your container (to update your service / micro-service) you will have to deal with adding your self-signed certificates, handling the files, storing them, etc.

Even if you want to do the TLS stuff with Nginx, I would suggest you put an Nginx reverse proxy on top of this image.

**Comment by Lijo050** [comment] 2018-02-14 02:38
@tiangolo thanks for the response, but I couldn't understand it clearly as Im still new to this field.

Following are my changes:
Dockerfile
```
FROM tiangolo/uwsgi-nginx-flask:python2.7

RUN apt-get update && \
    apt-get install -y openssl && \
    openssl genrsa -des3 -passout pass:x -out server.pass.key 2048 && \
    openssl rsa -passin pass:x -in server.pass.key -out /etc/ssl/server.key && \
    rm server.pass.key && \
    openssl req -new -key /etc/ssl/server.key -out /etc/ssl/server.csr \
        -subj "/C=UK/ST=Warwickshire/L=Leamington/O=OrgName/OU=IT Department/CN=example.com" && \
    openssl x509 -req -days 365  -in /etc/ssl/server.csr -signkey /etc/ssl/server.key -out /etc/ssl/server.crt

ENV LISTEN_PORT 443

COPY tmp.conf /etc/nginx/conf.d/tmp.conf

COPY ./app /app
```

tmp.conf
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    ssl_certificate /etc/ssl/server.crt;
    ssl_certificate_key /etc/ssl/server.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;


    # intermediate configuration. tweak to your needs.
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_prefer_server_ciphers on;

    # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
    add_header Strict-Transport-Security max-age=15768000;

    # OCSP Stapling ---
    # fetch OCSP records from URL in ssl_certificate and cache them
    ssl_stapling on;
    ssl_stapling_verify on;
}
```


and /app/main.py
```
from flask import Flask, request, Response
import os
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello World from Flask"

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 443))
    app.run(host='0.0.0.0', port=port, ssl_context= "adhoc")
```

**Comment by tiangolo** [comment] 2018-02-14 16:14
Is there any reason why you want to use self-signed certificates while you can get real HTTPS with Let's Encrypt?

**Comment by Lijo050** [comment] 2018-02-15 02:03
Due to some restrictions I can either use self signed certificate or an official certificate assigned by some Security firm. Can you provide some suggestion using self signed certificate or a way we can achieve this?

**Comment by tiangolo** [comment] 2018-02-15 05:56
Yep. I would still suggest a separate container (actually even more).

And I would still suggest Traefik.

Here are the docs for the relevant configuration: https://docs.traefik.io/configuration/entrypoints/

**Comment by seospace** [comment] 2018-02-16 14:28
What about https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion

**Comment by tiangolo** [comment] 2018-02-17 08:10
@seospace that doesn't use Docker labels, you would have to re-create the container every time.

With Traefik you can add labels to your services and it will pick them up, generate the TLS certificates and do the rest.

You could create a main Traefik service that listens to all the requests and generates all the certificates and everything. And make it generate TLS (SSL) certificates on demand, by checking the labels in your services.

You can check this section with a how to: https://github.com/senseta-os/senseta-base-project/blob/master/docker-swarm-cluster-deploy.md#traefik

**Comment by msghaleb** [comment] 2018-03-03 21:09
@Lijo050 
I agree that another container is a better design however to answer your question and eventually close this issue you just need to add the location to your server in other words your tmp.conf should look like that below:

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name YOURDOMAIN;
    ssl_certificate /etc/ssl/server.crt;
    ssl_certificate_key /etc/ssl/server.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;


    # intermediate configuration. tweak to your needs.
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_prefer_server_ciphers on;

    # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
    add_header Strict-Transport-Security max-age=15768000;

    # OCSP Stapling ---
    # fetch OCSP records from URL in ssl_certificate and cache them
    ssl_stapling on;
    ssl_stapling_verify on;
    location / {
      try_files $uri @app;
    }
    location @app {
      include uwsgi_params;
      uwsgi_pass unix:///tmp/uwsgi.sock;
    }
    location /static {
      alias /app/static;
    }
}

**Comment by msghaleb** [comment] 2018-03-21 07:49
@Lijo050 Perfect ;-) now you can close the issue ;-)

**Comment by tiangolo** [comment] 2018-04-18 05:54
It seems like the problem is solved :tada: , so I'll close this issue.

**Closed by tiangolo** 2018-04-18 05:54 UTC
