### ISSUE TITLE
[Question] Redirect loop

### ISSUE THREAD

**Issue by seospace** [tiangolo/uwsgi-nginx-flask-docker#40] opened 2018-02-16 14:17 UTC
I want to redirect all www to non-www.
I have this in my custom.conf file :

````
server {
        server_name www.domain.com;
        return 301 $scheme://domain.com$request_uri;
}
````

But i receive a redirect loop. Do you have any idea why is that?
I am using the container with [nginx-proxy](https://github.com/jwilder/nginx-proxy)
I think the issue happens beacuse there is double nginx-configuration.
One of nginx-proxy layer, second on uwsgi-nginx-flask-docker layer.

Isn't it better to just use pure uwsgi with nginx-proxy?

**Comment by tiangolo** [comment] 2018-02-17 08:22
Both Nginx configurations are independent in their own container.

Try to create a simple pure Nginx image: https://hub.docker.com/_/nginx/ with a simple index.html instead of your Flask app and see if that works. If it doesn't work, it means the problem is only in nginx-proxy.

If it works, it means the problem is in your Flask app or a combination with your Flask app and nginx-proxy.

The next thing to try would be to make your Flask app, using this image to listen directly, without nginx-proxy. If it works, the problem is probably in between nginx-proxy and this image. If it doesn't, the problem is probably in your custom configuration.

---

> Isn't it better to just use pure uwsgi with nginx-proxy?

Pure uWSGI would mean that it handles the requests directly, without a front end web server. But you can try that and see how it goes.

---

Just as a suggestion, I used nginx-proxy a long time ago and it worked pretty well for that time. But now I'm using Traefik and it has solved my use cases better. Including Let's encrypt certificate generation without downtime.

**Comment by seospace** [comment] 2018-02-17 09:29
@tiangolo thank you a lot for your detailed answer, best regards and thanks for the repos :)

**Comment by tiangolo** [comment] 2018-02-17 10:07
You're welcome!

I'm happy to help :smile: .

**Comment by tiangolo** [comment] 2018-04-18 05:59
It seems like the problem is solved, so I'll close this issue now.

**Closed by tiangolo** 2018-04-18 05:59 UTC
